### ISSUE TITLE
TargetElapsedTime TimeSpan.FromSeconds causes stuttering

### ISSUE THREAD

**Issue by EnemyArea** [willmotil/MonoGameUtilityClasses#1]
Hi ppl,

I've used the MgFrameRate lately in my own game to test some memory issues.
I walked through one of my cities and saw odd that stuttering I have never had before.
I disabled the MgFrameRate completely and its gone. A similar issue I was faced some time ago.
It was because of setting the TargetElapsedTime to a value generated by "TimeSpan.FromSeconds".
Even it is set to FromMilliseconds, it dont fix it completely, but FromTicks does. So I testet it with "TimeSpan.FromTicks(166666)" and the stuttering is gone.

**Comment by willmotil** [comment]
Thanks for this.

**Comment by willmotil** [comment]
I applied this change in the most recent upload though i believe most cases of stutters in monogame are not actually due to this itself.
